language: android

android:
  components:
    # Ref https://github.com/travis-ci/travis-ci/issues/6260.
    - tools
    - tools
    - platform-tools
    - build-tools-24.0.1
    - android-24
    - extra

after_script:
    - cat ./demo/build/outputs/lint-results.xml
    - cat ./threaddebugger/build/outputs/lint-results.xml
    - cat ./threadpool/build/outputs/lint-results.xml

sudo: false